# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      #- image: maven:3.6.0-jdk-8-alpine
      - image: circleci/openjdk:8-jdk-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v3-dependencies-

      - run: mvn dependency:go-offline

      - run: mvn clean package

      - save_cache:
          paths:
            - ~/.m2
          key: v3-dependencies-{{ checksum "pom.xml" }}
        

  #publish artifact to artifactory repo
  publish:
    docker:
      - image: maven:3.6.0-jdk-8-alpine
    working_directory: ~/repo

    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v3-publish-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v3-publish-dependencies-
      - run: mvn versions:set -DnewVersion=${CIRCLE_TAG}
      - run: mvn deploy


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  release:
    jobs:
      - publish:
          #only execute on a release/tag with a name that starts with v (eg. v0.1-alpha)
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
